spring:
  datasource:
    username: application
    password: '123app*.'
    url: jdbc:postgresql://localhost:5432/sodainventory
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082
logging:
  level:
    com:
      ms: debug
